### ISSUE TITLE
Is it recommended to fine-tune with only "i2v" mask type for i2v task?

### ISSUE THREAD

**Issue by junsukha** [PKU-YuanGroup/Open-Sora-Plan#534]
v1.3 says there're multiple mask types I can choose for I2V training.

If my only task is "i2v", is it recommended to fine-tune the model with the following mask config? i.e. set `i2v: 1` in `mask_type_ratio_dict_video` and the rest `0`?

```yaml
# mask processor args
min_clear_ratio: 0.8
max_clear_ratio: 1.0 

# mask_type_ratio_dict_video
mask_type_ratio_dict_video:
  t2iv: 0
  i2v: 1
  transition: 0
  continuation: 0
  clear: 0
  random_temporal: 0

mask_type_ratio_dict_image:
  t2iv: 0
  clear: 0
```
